#!/usr/bin/env bash
# Script that will display information about subdomains.

information() {
    about=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $about" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then 
    information "$1" "www"
    information "$1" "lb-01"
    information "$1" "web-01"
    information "$1" "web-02"
else
    information "$1" "$2"
fi

exit 0