#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -zcvf "$(date '+%m-%d-%Y').tar.gz" backup.sql