#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
a=$"Holberton"
b=$"School"
i=0
while [ $i -le 9 ]
do
    if [ $i = 9 ]
    then
	printf "Hi"
	printf "\n"
    fi
    printf "%s " $a
    printf "%s" $b
    printf "\n"
    i=$(( i+1 ))
done
