#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
a=$"Holberton"
b=$"School"
i=1
while [ $i -le 20 ]
do
    if [ $i = 5 ]
    then
	printf "bad luck from China"
	printf "\n"
    elif [ $i = 10 ]
    then
        printf "bad luck from Japan"
        printf "\n"
    elif [ $i = 18 ]
    then
        printf "bad luck from Italy"
        printf "\n"
    fi
    printf "%s" $i
    printf "\n"
    i=$(( i+1 ))
done
