#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
a=$"Holberton"
b=$"School"
i=1
while [ $i -le 20 ]
do
    case $i in
	5) printf "bad luck from China\n";;
	10) printf "bad luck from Japan\n";;
	18) printf "bad luck from Italy\n";;
    esac
    printf "%s" $i
    printf "\n"
    i=$(( i+1 ))
done
