#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
f="holbertonschool"
if [ -e ./$f ];
then
    echo "$f file exists"
	if [ ! -s ./$f ];
	then
	    printf "holbertonschool file is empty\n"
	else
	    printf "holbertonschool file is not empty\n"
	fi
	if [ ! -d ./$f ];
	then
		echo "$f is a regular file"
	fi
else
    echo "$f file does not exist"
fi
