#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
f="holbertonschool"
if [ -e ./$f ];
then
    echo "$f file exists"
	if [ ! -s ./$f ];
	then
	    echo "holbertonschool file is empty"
	else
	    echo "holbertonschool file is not empty"
	fi
	if [ ! -d ./$f ];
	then
		echo "$f is a regular file"
	fi
else
    echo "$f file does not exist"
fi
